name    'herokuconfig'
version '1.0.0'
source  'https://github.com/cloudability/herokuconfig'
author  'E.J. Finneran'
license 'MIT License'
summary 'Puppet module to retrieve config variables from Heroku'
description 'Puppet module to retrieve config variables from Heroku and write them to a file'
description 'Puppet module to retrieve files from a cloud provider'
project_page 'https://github.com/cloudability/herokuconfig'
